export const Family = {
    // Mammifères
    CANIDAE: "CANIDAE",
    BOVIDAE: "BOVIDAE",
    LEPORIDAE: "LEPORIDAE",
    HOMINIDAE: "HOMINIDAE",
    SCIURIDAE: "SCIURIDAE",
    PHASCOLARCTIDAE: "PHASCOLARCTIDAE",
    DELPHINIDAE: "DELPHINIDAE",
    MURIDAE: "MURIDAE",
    VESPERTILIONIDAE: "VESPERTILIONIDAE",
    ERINACEIDAE: "ERINACEIDAE",
    FELIDAE: "FELIDAE",

    // Oiseaux
    SPHENISCIDAE: "SPHENISCIDAE",
    ACCIPITRIDAE: "ACCIPITRIDAE",
    COLUMBIDAE: "COLUMBIDAE",
    CORVIDAE: "CORVIDAE",

    // Reptiles
    TESTUDINIDAE: "TESTUDINIDAE",
    CHAMAELEONIDAE: "CHAMAELEONIDAE",
    VIPERIDAE: "VIPERIDAE",
    IGUANIDAE: "IGUANIDAE",

    // Insectes
    COCCINELLIDAE: "COCCINELLIDAE",
    FORMICIDAE: "FORMICIDAE",
    APIDAE: "APIDAE",
    VESPIDAE: "VESPIDAE",
    SCARABAEIDAE: "SCARABAEIDAE",
    PAPILIONIDAE: "PAPILIONIDAE",
    NYMPHALIDAE: "NYMPHALIDAE",
    PIERIDAE: "PIERIDAE",
    THERAPHOSIDAE: "THERAPHOSIDAE",

    // Plantes
    ASTERACEAE: "ASTERACEAE",
    FAGACEAE: "FAGACEAE",
    MALVACEAE: "MALVACEAE",
    LAMIACEAE: "LAMIACEAE",
    SAPINDACEAE: "SAPINDACEAE",
    ROSACEAE: "ROSACEAE",
    FABACEAE: "FABACEAE",
    POACEAE: "POACEAE",

    // Autres
    UNKNOWN: "UNKNOWN"
} as const;

export type Family = typeof Family[keyof typeof Family];