kind: pipeline
type: docker
name: FFGO-CI

trigger:
  event:
    - push

steps:
  - name: app-build
    image: node:latest
    commands:
      - npm install

  - name: typescript-check
    image: node:latest
    commands:
      - npm install
      - npx tsc --noEmit
    depends_on: [ app-build ]

  - name: test
    image: node:latest
    commands:
      - npm install
      - NODE_ENV=test npm run test:ci --forceExit
    depends_on: [ typescript-check ]

  - name: code-analysis
    image: node:latest
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
    settings:
      sources: .
    commands:
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
      - sonar-scanner -D sonar.projectKey=FFGO -D sonar.sources=. -D sonar.exclusions=**/__tests__/**,**/*.spec.ts,**/*.test.ts,**/app/**,**/hook/**,**hook** -D sonar.javascript.lcov.reportPaths=./__tests__/coverage/lcov.info -D sonar.host.url=https://codefirst.iut.uca.fr/sonar
    depends_on: [ test ]