import EncyclopediaScreen from "@/screens/EncyclopediaScreen";
import {Image} from "react-native";

export class Specie  {
  id: number;
  name: string;
  scientificName: string;
  description: string;
  image: string;

  constructor(id: number, name: string, scientificName: string, description: string, image: string) {
    this.id = id;
    this.name = name;
    this.scientificName = scientificName;
    this.description = description;
    this.image = image;
  }
}
export default function Encyclopedia() {
  const species = [
      new Specie(1,"Eurylaime vert","Calyptomena viridis","Petit oiseau vert tout mignon, tout choupi",
          "https://s3.animalia.bio/animals/photos/full/1.25x1/lesser-green-broadbill-7150956749jpg.webp?id=7bb2b71f1c8886f6aba586e7d27a85a5"),
      new Specie(2,"Coccinelle","Coccinella","Petit insect rouge et noir",
          "https://s3.animalia.bio/animals/photos/full/1.25x1/2560px-ladybird-2562155830.webp?id=4746a43a8119d39733d3525585e19553"),
      new Specie(3,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(4,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(5,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(6,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(7,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(8,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(9,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(10,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(11,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(12,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(13,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(14,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(15,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(16,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),
      new Specie(17,"Écureuil gris","Sciurus carolinensis","L'Écureuil gris (Sciurus carolinensis) est une espèce de mammifères rongeurs arboricoles, commun dans l'Est de l'Amérique du Nord. Généralement gris, il peut aussi avoir un pelage brun, noir ou, plus rarement, blanc ou cannelle. L'Écureuil gris est très abondant notamment dans la grande région de Montréal alors qu'il est majoritairement brun, plus ou moins foncé, à Toronto.","https://s3.animalia.bio/animals/photos/full/1.25x1/1200px-sciurus-carolinensis-gotigersjfjpg.webp?id=ebc407568eff02cd06c9edf17b71ec10"),

  ]
  return (
      <EncyclopediaScreen species={species}/>
  );
}

